EXTRA_IMAGE_FEATURES += "debug-tweaks"

# Networking: ip/ss tools, DHCP client, WiFi supplicant, RTL8125B NIC firmware
IMAGE_INSTALL:append = " iproute2 dhcpcd wpa-supplicant linux-firmware-rtl-nic linux-firmware-whence-license"
