#@TYPE: Machine
#@NAME: Radxa Rock 5B (RK3588)
#@DESCRIPTION: Radxa Rock 5B with RK3588 SoC

DEFAULTTUNE = "cortexa76-cortexa55"
require conf/machine/include/arm/armv8-2a/tune-cortexa76-cortexa55.inc

MACHINE_FEATURES = "usbhost usbgadget alsa screen wifi bluetooth"

SERIAL_CONSOLES = "1500000;ttyS2"

IMAGE_FSTYPES = "ext4"
